autoload -U colors && colors

source ~/.utils.sh
source $DOTFILES/zsh/custom/config/functions.zsh
try_source ~/.functions.zsh

# export DEBUG_LEVEL=0
debug 'zshenv' '~/.zshenv'

# Common AWK source
try_source $DOTFILES/zsh/custom/config/export.zsh
try_source ~/.zsh_export
