autoload -U colors && colors

source ~/.utils.sh
source $DOTFILES/zsh/custom/config/functions.zsh
try_source ~/.functions.zsh

debug 'zshenv' '~/.zshenv'

try_source $DOTFILES/zsh/custom/config/export.zsh
try_source ~/.zsh_export
